### ISSUE TITLE
Create a log all runs for later analysis

### ISSUE THREAD

**Issue by zachleat** [zachleat/performance-leaderboard#1]
Per feedback here it would be nice to see a full log of all of the runs, rather than throwing non-median runs away (should later analysis be needed)

https://twitter.com/reubenlillie/status/1241866530591301632

cc @reubenlillie

**Comment by reubenlillie** [comment]
First, I'm flattered to be part of issue no. 1. Second, it'd also be helpful have logs for further statistical analysis, such as standard deviations, outliers, and so forth.

**Comment by zachleat** [comment]
Shipped with 1.0.2
