### ISSUE TITLE
api.websitecarbon.com is no longer returning data

### ISSUE THREAD

**Issue by zachleat** [zachleat/performance-leaderboard#15]
cc @dgrammatiko 

I don’t know if this is an official API or not but I think we may need to remove the carbon testing part, unfortunately.

**Comment by zachleat** [comment]
added in https://github.com/zachleat/performance-leaderboard/pull/8

**Comment by dgrammatiko** [comment]
Oh, that's bad. FWIW there's already an issue upstream: https://gitlab.com/wholegrain/carbon-api-2-0/-/issues/12

I will research this a bit more tomorrow and see if I can do a PR upstream or just remove it here

**Comment by dgrammatiko** [comment]
@zachleat unfortunately the news are not good on their side, so here's a PR #16 to remove the redundant code.

Maybe you might want to wait few days as there's a response pending on their side: https://gitlab.com/wholegrain/carbon-api-2-0/-/issues/12#note_706248558
