### ISSUE TITLE
Use the pagespeed insights API for faster performance

### ISSUE THREAD

**Issue by zachleat** [zachleat/performance-leaderboard#19]
https://dev.to/philw_/show-off-your-lighthouse-scores-in-eleventy-with-the-pagespeed-insights-api-1cpp

https://developers.google.com/speed/docs/insights/v5/get-started

**Comment by zachleat** [comment]
Published this as a separate module: https://github.com/zachleat/performance-leaderboard-pagespeed-insights/

**Comment by nhoizey** [comment]
With many clients relying on PageSpeed Insight to know how "fast" their site is, I've noticed that its Lighthouse scores are really unstable, with sometimes 20 points differences just a few minutes apart… 🤷‍♂️

So I'm glad you chose to put this elsewhere! 😅

**Comment by zachleat** [comment]
yeah, I definitely can echo this sentiment. The numbers are… not reliable. And worse, they are cached on the server so it’s hard to even do a median run selection across multiple runs.
