### ISSUE TITLE
Testing one site getting two different speedindices

### ISSUE THREAD

**Issue by octoxalis** [zachleat/performance-leaderboard#2]
When I run **performance-leaderboard** to test only one of my 11ty sites, first without any number of pass `console.log( await PerfLeaderboard(urls) );`
 and second with 5 passes  `console.log( await PerfLeaderboard(urls, 5) );`, I get a big difference (43%) between the first one (3 passes) and the second one (5 passes).

Here is the log:
```
Testing 1 sites:
(Site 1 of 1, run 1 of 3): https://corsa.netlify.app/posts/unfolding.html
(Site 1 of 1, run 2 of 3): https://corsa.netlify.app/posts/unfolding.html
(Site 1 of 1, run 3 of 3): https://corsa.netlify.app/posts/unfolding.html
[
  {
    url: 'https://corsa.netlify.app/posts/unfolding.html',
    finalUrl: 'https://corsa.netlify.app/posts/unfolding.html',
    lighthouseScore: 1,
    firstContentfulPaint: 1156.5130000000001,
    firstMeaningfulPaint: 1156.5130000000001,
    speedIndex: 1395.6202760075153,
    rank: 1
  }
]
Testing 1 sites:
(Site 1 of 1, run 1 of 5): https://corsa.netlify.app/posts/unfolding.html
(Site 1 of 1, run 2 of 5): https://corsa.netlify.app/posts/unfolding.html
(Site 1 of 1, run 3 of 5): https://corsa.netlify.app/posts/unfolding.html
(Site 1 of 1, run 4 of 5): https://corsa.netlify.app/posts/unfolding.html
(Site 1 of 1, run 5 of 5): https://corsa.netlify.app/posts/unfolding.html
[
  {
    url: 'https://corsa.netlify.app/posts/unfolding.html',
    finalUrl: 'https://corsa.netlify.app/posts/unfolding.html',
    lighthouseScore: 1,
    firstContentfulPaint: 969.73,
    firstMeaningfulPaint: 991.73,
    speedIndex: 969.73,
    rank: 1
  }
]

```

At the same time, **DevTools Lighthouse** gives me a result similar to the second one (speedIndex: 0.9s).

Is there any explanation?

**Comment by zachleat** [comment]
This selects the median of the three runs. It is variable, so the more runs the better.

You can read more at the Lighthouse docs https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md

**Comment by zachleat** [comment]
This is probably a Lighthouse question—if those docs don’t help please file an issue on their tracker! Thanks!
